name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write # Cấp quyền ghi để tạo Release và upload file

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build and Release
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: true
          # Nếu build cho macOS trên GitHub Actions, nó sẽ tự động dùng môi trường macos-latest
          # Nếu build cho Windows, nó sẽ dùng windows-latest
